"""Sensor platform for Intervals.icu."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntity,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import (
    UnitOfMass,
    UnitOfTime,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.device_registry import DeviceEntryType, DeviceInfo
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import CONF_ATHLETE_ID, DOMAIN
from .coordinator import IntervalsIcuCoordinator, IntervalsIcuData


@dataclass(frozen=True, kw_only=True)
class IntervalsIcuSensorEntityDescription(SensorEntityDescription):
    """Describe an Intervals.icu sensor."""

    value_fn: Callable[[IntervalsIcuData], Any]
    available_fn: Callable[[IntervalsIcuData], bool] = lambda _data: True
    attrs_fn: Callable[[IntervalsIcuData], dict[str, Any] | None] | None = None


def _wellness_value(key: str) -> Callable[[IntervalsIcuData], Any]:
    """Create a value function for a wellness field."""

    def _get(data: IntervalsIcuData) -> Any:
        if data.wellness is None:
            return None
        return data.wellness.get(key)

    return _get


def _wellness_available(key: str) -> Callable[[IntervalsIcuData], bool]:
    """Create an available function for a wellness field."""

    def _check(data: IntervalsIcuData) -> bool:
        if data.wellness is None:
            return False
        return data.wellness.get(key) is not None

    return _check


def _latest_activity_value(key: str) -> Callable[[IntervalsIcuData], Any]:
    """Create a value function for the latest activity field.

    ``data.latest_activity`` is guaranteed to be the newest record because the
    coordinator sorts activities explicitly rather than trusting the API order.
    """

    def _get(data: IntervalsIcuData) -> Any:
        activity = data.latest_activity
        if activity is None:
            return None
        return activity.get(key)

    return _get


def _latest_activity_available(data: IntervalsIcuData) -> bool:
    return data.latest_activity is not None


def _next_event_value(key: str) -> Callable[[IntervalsIcuData], Any]:
    """Create a value function for the next planned workout."""

    def _get(data: IntervalsIcuData) -> Any:
        workout = data.next_workout
        if workout is None:
            return None
        return workout.get(key)

    return _get


def _next_event_available(data: IntervalsIcuData) -> bool:
    return data.next_workout is not None


def _form_value(data: IntervalsIcuData) -> float | None:
    """Calculate form (TSB) = CTL - ATL."""
    if data.wellness is None:
        return None
    ctl = data.wellness.get("ctl")
    atl = data.wellness.get("atl")
    if ctl is None or atl is None:
        return None
    return round(ctl - atl, 1)


def _form_available(data: IntervalsIcuData) -> bool:
    """Check if form can be calculated."""
    if data.wellness is None:
        return False
    return data.wellness.get("ctl") is not None and data.wellness.get("atl") is not None


def _athlete_value(key: str) -> Callable[[IntervalsIcuData], Any]:
    """Create a value function for an athlete top-level field."""

    def _get(data: IntervalsIcuData) -> Any:
        return data.athlete.get(key)

    return _get


def _sport_setting_value(key: str) -> Callable[[IntervalsIcuData], Any]:
    """Create a value function for a field in the default sport settings.

    Kept for backwards compatibility with the athlete profile sensors that
    describe whichever sport settings entry the API lists first. Per-sport
    sensors are generated by ``_sport_setting_sensors`` instead.
    """

    def _get(data: IntervalsIcuData) -> Any:
        settings = data.athlete.get("sportSettings")
        if not settings:
            return None
        return settings[0].get(key)

    return _get


def _sport_setting_available(key: str) -> Callable[[IntervalsIcuData], bool]:
    """Create an available function for a field in the default sport settings."""

    def _check(data: IntervalsIcuData) -> bool:
        settings = data.athlete.get("sportSettings")
        if not settings:
            return False
        return settings[0].get(key) is not None

    return _check


def _sport_setting_sports(data: IntervalsIcuData) -> list[tuple[str, dict[str, Any]]]:
    """Return ``(sport_type, settings)`` pairs in a stable order.

    ``sportSettings`` holds one entry per sport (Ride, Run, Swim, ...), each
    with its own FTP, LTHR and max HR. Reading only ``sportSettings[0]`` means
    a multi-sport athlete silently loses every sport but the first. Enumerating
    all of them produces one set of sensors per sport instead.
    """
    settings = data.athlete.get("sportSettings") or []
    pairs: list[tuple[str, dict[str, Any]]] = []
    for entry in settings:
        if not isinstance(entry, dict):
            continue
        sport = entry.get("type") or entry.get("sport") or "Default"
        pairs.append((str(sport), entry))
    pairs.sort(key=lambda pair: pair[0])
    return pairs


def _sport_setting_value_for(
    sport: str, key: str
) -> Callable[[IntervalsIcuData], Any]:
    """Create a value function for a specific sport's settings field."""

    def _get(data: IntervalsIcuData) -> Any:
        for name, entry in _sport_setting_sports(data):
            if name == sport:
                return entry.get(key)
        return None

    return _get


def _sport_setting_available_for(
    sport: str, key: str
) -> Callable[[IntervalsIcuData], bool]:
    """Create an available function for a specific sport's settings field."""

    def _check(data: IntervalsIcuData) -> bool:
        for name, entry in _sport_setting_sports(data):
            if name == sport:
                return entry.get(key) is not None
        return False

    return _check


SENSOR_DESCRIPTIONS: tuple[IntervalsIcuSensorEntityDescription, ...] = (
    # Wellness sensors
    IntervalsIcuSensorEntityDescription(
        key="weight",
        translation_key="weight",
        native_unit_of_measurement=UnitOfMass.KILOGRAMS,
        device_class=SensorDeviceClass.WEIGHT,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("weight"),
        available_fn=_wellness_available("weight"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="resting_hr",
        translation_key="resting_hr",
        native_unit_of_measurement="bpm",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("restingHR"),
        available_fn=_wellness_available("restingHR"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="hrv",
        translation_key="hrv",
        native_unit_of_measurement="ms",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("hrv"),
        available_fn=_wellness_available("hrv"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="sleep_time",
        translation_key="sleep_time",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("sleepSecs"),
        available_fn=_wellness_available("sleepSecs"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="sleep_score",
        translation_key="sleep_score",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("sleepScore"),
        available_fn=_wellness_available("sleepScore"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="readiness",
        translation_key="readiness",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("readiness"),
        available_fn=_wellness_available("readiness"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="spo2",
        translation_key="spo2",
        native_unit_of_measurement="%",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("spO2"),
        available_fn=_wellness_available("spO2"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="steps",
        translation_key="steps",
        native_unit_of_measurement="steps",
        state_class=SensorStateClass.TOTAL_INCREASING,
        value_fn=_wellness_value("steps"),
        available_fn=_wellness_available("steps"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="ctl",
        translation_key="ctl",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("ctl"),
        available_fn=_wellness_available("ctl"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="atl",
        translation_key="atl",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("atl"),
        available_fn=_wellness_available("atl"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="ramp_rate",
        translation_key="ramp_rate",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("rampRate"),
        available_fn=_wellness_available("rampRate"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="form",
        translation_key="form",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_form_value,
        available_fn=_form_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="stress",
        translation_key="stress",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("stress"),
        available_fn=_wellness_available("stress"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="mood",
        translation_key="mood",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("mood"),
        available_fn=_wellness_available("mood"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="motivation",
        translation_key="motivation",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("motivation"),
        available_fn=_wellness_available("motivation"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="fatigue",
        translation_key="fatigue",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("fatigue"),
        available_fn=_wellness_available("fatigue"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="soreness",
        translation_key="soreness",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("soreness"),
        available_fn=_wellness_available("soreness"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="hrv_sdnn",
        translation_key="hrv_sdnn",
        native_unit_of_measurement="ms",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("hrvSDNN"),
        available_fn=_wellness_available("hrvSDNN"),
    ),
    IntervalsIcuSensorEntityDescription(
        key="kcal_consumed",
        translation_key="kcal_consumed",
        native_unit_of_measurement="kcal",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_wellness_value("kcalConsumed"),
        available_fn=_wellness_available("kcalConsumed"),
    ),
    # Latest activity sensors
    IntervalsIcuSensorEntityDescription(
        key="last_activity_name",
        translation_key="last_activity_name",
        value_fn=_latest_activity_value("name"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_type",
        translation_key="last_activity_type",
        value_fn=_latest_activity_value("type"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_duration",
        translation_key="last_activity_duration",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        device_class=SensorDeviceClass.DURATION,
        value_fn=_latest_activity_value("moving_time"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_distance",
        translation_key="last_activity_distance",
        native_unit_of_measurement="m",
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_latest_activity_value("distance"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_training_load",
        translation_key="last_activity_training_load",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_latest_activity_value("icu_training_load"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_avg_hr",
        translation_key="last_activity_avg_hr",
        native_unit_of_measurement="bpm",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_latest_activity_value("average_heartrate"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_max_hr",
        translation_key="last_activity_max_hr",
        native_unit_of_measurement="bpm",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_latest_activity_value("max_heartrate"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_avg_power",
        translation_key="last_activity_avg_power",
        native_unit_of_measurement="W",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_latest_activity_value("icu_average_watts"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_np",
        translation_key="last_activity_np",
        native_unit_of_measurement="W",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_latest_activity_value("icu_weighted_avg_watts"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_intensity",
        translation_key="last_activity_intensity",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_latest_activity_value("icu_intensity"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_calories",
        translation_key="last_activity_calories",
        native_unit_of_measurement="kcal",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_latest_activity_value("calories"),
        available_fn=_latest_activity_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="last_activity_elevation",
        translation_key="last_activity_elevation",
        native_unit_of_measurement="m",
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_latest_activity_value("total_elevation_gain"),
        available_fn=_latest_activity_available,
    ),
    # Next planned workout sensors
    IntervalsIcuSensorEntityDescription(
        key="next_workout_name",
        translation_key="next_workout_name",
        value_fn=_next_event_value("name"),
        available_fn=_next_event_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="next_workout_date",
        translation_key="next_workout_date",
        device_class=SensorDeviceClass.DATE,
        value_fn=_next_event_value("start_date_local"),
        available_fn=_next_event_available,
    ),
    IntervalsIcuSensorEntityDescription(
        key="next_workout_type",
        translation_key="next_workout_type",
        value_fn=_next_event_value("type"),
        available_fn=_next_event_available,
    ),
    # Athlete fitness metrics. FTP, LTHR and max HR are per-sport values and
    # are generated one set per entry in the athlete's sportSettings by
    # ``_sport_setting_sensors``; only the sport-independent profile fields
    # belong in the static list below.
    IntervalsIcuSensorEntityDescription(
        key="resting_hr_athlete",
        translation_key="resting_hr_athlete",
        native_unit_of_measurement="bpm",
        state_class=SensorStateClass.MEASUREMENT,
        value_fn=_athlete_value("icu_resting_hr"),
        available_fn=lambda data: data.athlete.get("icu_resting_hr") is not None,
    ),
)


# Fields that are defined per sport in ``sportSettings``.
_SPORT_FIELDS: tuple[tuple[str, str, str, object], ...] = (
    # (field key, unit, device class, translation key)
    ("ftp", "W", SensorDeviceClass.POWER, "ftp"),
    ("lthr", "bpm", None, "lthr"),
    ("max_hr", "bpm", None, "max_hr"),
)


def _sport_setting_sensors(
    data: IntervalsIcuData,
) -> tuple[IntervalsIcuSensorEntityDescription, ...]:
    """Build one FTP/LTHR/max HR sensor set per configured sport.

    ``unique_id`` and the display name both carry the sport type so that a
    multi-sport athlete (for example cycling with FTP 280 W and running with
    FTP 250 W) gets a distinct, unambiguous sensor for each instead of only
    ever seeing whichever entry the API returned first.

    The sport is passed to the translation as a ``sport`` placeholder. The
    entity ID is built from the raw API sport name via ``_slugify`` so it stays
    stable if the displayed translation ever changes.
    """
    descriptions: list[IntervalsIcuSensorEntityDescription] = []
    for sport, _settings in _sport_setting_sports(data):
        slug = _slugify(sport)
        for field_key, unit, device_class, translation_key in _SPORT_FIELDS:
            kwargs: dict[str, Any] = {
                "key": f"{field_key}_{slug}",
                "translation_key": translation_key,
                "translation_placeholders": {"sport": sport},
                "name": f"{sport} {field_key.upper().replace('_', ' ')}",
                "native_unit_of_measurement": unit,
                "state_class": SensorStateClass.MEASUREMENT,
                "value_fn": _sport_setting_value_for(sport, field_key),
                "available_fn": _sport_setting_available_for(sport, field_key),
            }
            if device_class is not None:
                kwargs["device_class"] = device_class
            descriptions.append(IntervalsIcuSensorEntityDescription(**kwargs))
    return tuple(descriptions)


# Display names for the sport types Intervals.icu reports in ``sportSettings``.
# Home Assistant substitutes the ``{sport}`` placeholder with a plain string and
# cannot translate it, so the localized label is resolved here. Entity IDs are
# derived from ``_slugify(sport)`` and are unaffected by this mapping, which
# keeps already-registered entities stable.
SPORT_DISPLAY_NAMES: dict[str, str] = {
    "Ride": "骑行",
    "Run": "跑步",
    "Swim": "游泳",
    "Walk": "步行",
    "Hike": "徒步",
    "Row": "划船",
    "Ski": "滑雪",
    "WeightTraining": "力量训练",
    "Workout": "训练",
    "Rowing": "划船",
    "VirtualRide": "虚拟骑行",
    "VirtualRun": "虚拟跑步",
    "EBikeRide": "电动自行车",
    "MountainBikeRide": "山地骑行",
    "GravelRide": "砂石骑行",
    "TrailRun": "越野跑",
    "TrackRun": "场地跑",
    "Treadmill": "跑步机",
    "IndoorCycling": "室内骑行",
    "NordicSki": "越野滑雪",
    "AlpineSki": "高山滑雪",
    "SwimOpenWater": "公开水域游泳",
    "Soccer": "足球",
    "Tennis": "网球",
    "Basketball": "篮球",
    "Yoga": "瑜伽",
    "Pilates": "普拉提",
    "Other": "其他",
}

# Traditional Chinese variants for the sports whose glyphs differ.
SPORT_DISPLAY_NAMES_HANT: dict[str, str] = {
    "Ride": "騎行",
    "Swim": "游泳",
    "Walk": "步行",
    "Hike": "徒步",
    "Row": "划船",
    "Ski": "滑雪",
    "WeightTraining": "力量訓練",
    "Workout": "訓練",
    "Rowing": "划船",
    "VirtualRide": "虛擬騎行",
    "VirtualRun": "虛擬跑步",
    "EBikeRide": "電動自行車",
    "MountainBikeRide": "山地騎行",
    "GravelRide": "砂石騎行",
    "TrailRun": "越野跑",
    "TrackRun": "場地跑",
    "Treadmill": "跑步機",
    "IndoorCycling": "室內騎行",
    "NordicSki": "越野滑雪",
    "AlpineSki": "高山滑雪",
    "SwimOpenWater": "公開水域游泳",
    "Soccer": "足球",
    "Tennis": "網球",
    "Basketball": "籃球",
    "Yoga": "瑜伽",
    "Pilates": "普拉提",
    "Other": "其他",
}


def localize_sport(sport: str, language: str | None = None) -> str:
    """Return a display label for a sport type.

    Only Simplified and Traditional Chinese labels are provided; every other
    language falls back to the raw API value, which is already the English
    spelling used by Intervals.icu.
    """
    if language is None:
        return SPORT_DISPLAY_NAMES.get(sport, sport)
    if language.startswith("zh-Hant") or language.startswith("zh-TW"):
        return SPORT_DISPLAY_NAMES_HANT.get(
            sport, SPORT_DISPLAY_NAMES.get(sport, sport)
        )
    if language.startswith("zh"):
        return SPORT_DISPLAY_NAMES.get(sport, sport)
    return sport


def _slugify(value: str) -> str:
    """Lowercase a sport name into a stable identifier fragment."""
    return "".join(ch if ch.isalnum() else "_" for ch in value.lower()).strip("_")


_NAMED_DISTANCES: tuple[tuple[float, str], ...] = (
    (1609.34, "1 mile"),
    (3218.69, "2 miles"),
    (5000.0, "5k"),
    (10000.0, "10k"),
    (16093.4, "10 miles"),
    (21097.5, "half marathon"),
    (42195.0, "marathon"),
)


def _format_distance(meters: float) -> str:
    """Format a distance in meters as a short human-readable label."""
    for value, label in _NAMED_DISTANCES:
        if abs(meters - value) < 1.0:
            return label
    if meters >= 1000:
        km = meters / 1000
        if km == int(km):
            return f"{int(km)}k"
        return f"{km:g}k"
    return f"{round(meters)}m"


def _best_effort_value(index: int) -> Callable[[IntervalsIcuData], Any]:
    """Create a value function for the best effort at a distance index."""

    def _get(data: IntervalsIcuData) -> Any:
        curve = data.pace_curve
        if not curve:
            return None
        values = curve.get("values") or []
        if index >= len(values):
            return None
        return values[index]

    return _get


def _best_effort_available(index: int) -> Callable[[IntervalsIcuData], bool]:
    """Return True when the pace curve has a value at the given index."""

    def _check(data: IntervalsIcuData) -> bool:
        curve = data.pace_curve
        if not curve:
            return False
        values = curve.get("values") or []
        return index < len(values) and values[index] is not None

    return _check


def _best_effort_attrs(
    index: int,
) -> Callable[[IntervalsIcuData], dict[str, Any] | None]:
    """Return the activity id/name/date that set the best effort at this index."""

    def _get(data: IntervalsIcuData) -> dict[str, Any] | None:
        curve = data.pace_curve
        if not curve:
            return None
        activity_ids = curve.get("activity_id") or []
        if index >= len(activity_ids):
            return None
        activity_id = activity_ids[index]
        return {"activity_id": activity_id}

    return _get


def _best_effort_sensors(
    data: IntervalsIcuData,
) -> tuple[IntervalsIcuSensorEntityDescription, ...]:
    """Build one sensor description per distance in the pace curve."""
    curve = data.pace_curve
    if not curve:
        return ()
    distances = curve.get("distance") or []
    return tuple(
        IntervalsIcuSensorEntityDescription(
            key=f"best_effort_{round(meters)}m",
            name=f"Best effort {_format_distance(meters)}",
            native_unit_of_measurement=UnitOfTime.SECONDS,
            device_class=SensorDeviceClass.DURATION,
            state_class=SensorStateClass.MEASUREMENT,
            value_fn=_best_effort_value(index),
            available_fn=_best_effort_available(index),
            attrs_fn=_best_effort_attrs(index),
        )
        for index, meters in enumerate(distances)
    )


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up Intervals.icu sensors from a config entry."""
    coordinator: IntervalsIcuCoordinator = hass.data[DOMAIN][entry.entry_id]
    athlete_id = entry.data[CONF_ATHLETE_ID]

    added_keys: set[str] = set()

    def _build_descriptions() -> tuple[IntervalsIcuSensorEntityDescription, ...]:
        return (
            SENSOR_DESCRIPTIONS
            + _sport_setting_sensors(coordinator.data)
            + _best_effort_sensors(coordinator.data)
        )

    def _add_new_entities() -> None:
        """Create entities for descriptions that appeared after setup.

        The per-sport and best-effort sensor sets are derived from live data:
        a new sport configured in Intervals.icu, or a new distance appearing in
        the pace curve, produces descriptions that did not exist during the
        initial setup. Without this listener those sensors would stay missing
        until the integration was reloaded by hand.
        """
        new_descriptions = [
            description
            for description in _build_descriptions()
            if description.key not in added_keys
        ]
        if not new_descriptions:
            return
        added_keys.update(description.key for description in new_descriptions)
        async_add_entities(
            IntervalsIcuSensor(coordinator, description, athlete_id)
            for description in new_descriptions
        )

    initial_descriptions = _build_descriptions()
    added_keys.update(description.key for description in initial_descriptions)
    async_add_entities(
        IntervalsIcuSensor(coordinator, description, athlete_id)
        for description in initial_descriptions
    )

    entry.async_on_unload(coordinator.async_add_listener(_add_new_entities))


class IntervalsIcuSensor(CoordinatorEntity[IntervalsIcuCoordinator], SensorEntity):
    """Representation of an Intervals.icu sensor."""

    entity_description: IntervalsIcuSensorEntityDescription
    _attr_has_entity_name = True

    def __init__(
        self,
        coordinator: IntervalsIcuCoordinator,
        description: IntervalsIcuSensorEntityDescription,
        athlete_id: str,
    ) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator)
        self.entity_description = description
        self._attr_unique_id = f"{athlete_id}_{description.key}"
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, athlete_id)},
            name="Intervals.icu",
            manufacturer="Intervals.icu",
            entry_type=DeviceEntryType.SERVICE,
        )

    @property
    def translation_placeholders(self) -> dict[str, str] | None:
        """Localize the ``{sport}`` placeholder before Home Assistant renders it.

        Home Assistant inserts placeholder values verbatim into the translated
        template; it never translates them. The sport type therefore has to be
        localized here, otherwise a Chinese UI would render a mixed-language
        name such as "Ride 阈值功率".
        """
        placeholders = self.entity_description.translation_placeholders
        if not placeholders or "sport" not in placeholders:
            return placeholders

        language = getattr(self.hass.config, "language", None) if self.hass else None
        return {
            **placeholders,
            "sport": localize_sport(placeholders["sport"], language),
        }

    @property
    def native_value(self) -> Any:
        """Return the state of the sensor."""
        return self.entity_description.value_fn(self.coordinator.data)

    @property
    def available(self) -> bool:
        """Return True if entity is available."""
        if not super().available:
            return False
        return self.entity_description.available_fn(self.coordinator.data)

    @property
    def extra_state_attributes(self) -> dict[str, Any] | None:
        """Return additional state attributes, if the description provides them."""
        if self.entity_description.attrs_fn is None:
            return None
        return self.entity_description.attrs_fn(self.coordinator.data)
